version: "3.9"

services:
  article-authentication-service:
    image: quay.io/keycloak/keycloak:19.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    entrypoint:
      - /opt/keycloak/bin/kc.sh
      - start-dev
      - --http-port=8888
      - --http-relative-path=/auth
      - --import-realm

    ports:
      - "8888:8888"


